sonar.projectKey=churn-app
sonar.organization=shivendrasingh01
sonar.projectName=Churn App
sonar.sources=app,model
sonar.tests=tests
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.exclusions=reports/**,data/**,model/*.pkl
