sonar.projectKey=ShivendraSingh01_advance-assignment
sonar.organization=shivendrasingh01
sonar.projectName=advance-assignment
sonar.sources=app,model
sonar.tests=tests
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.exclusions=reports/**,data/**,model/*.pkl
